### ISSUE TITLE
Proxy server Autorization

### ISSUE THREAD

**Issue by SergeyIlyin** [pds-technology/witsml-studio#1]
There no setting to proxy server autorization

**Comment by StreckerCM** [comment]
This is definitely needed!

**Comment by bmdiaz** [comment]
Thank you for your feedback and patience!  We have recently added Proxy and Security settings tabs to the connection dialog.

![image](https://cloud.githubusercontent.com/assets/235309/24232029/2160d050-0f56-11e7-97f7-ee42d2405b8b.png)

![image](https://cloud.githubusercontent.com/assets/235309/24232056/4e2ee248-0f56-11e7-8965-fc72988823fa.png)

**Comment by StreckerCM** [comment]
The version I had must have not been updating It was still called PDS.WITSMLstudio (not PDS.WITSMLstudio.Desktop) in the program files.  I downloaded the latest version from the downloads link on Git Hub and now I have these options.

However I am still having a problem authenticating to the proxy.  Maybe it is because I need to use AD authentication?

Here is the log file that was produced:
[PDS.WITSMLstudio.Desktop.log.txt](https://github.com/pds-technology/witsml-studio/files/864899/PDS.WITSMLstudio.Desktop.log.txt)

**Comment by bmdiaz** [comment]
We recently rebranded the open source applications under the WITSMLstudio name, sorry for the inconvenience.  You can also install the latest version using our [click-once installer](https://witsml.pds.technology/studio/click-once/).

Have you tried leaving the proxy username/password blank and only specifying the host/port?

**Comment by StreckerCM** [comment]
I just tried that and it still gives me connection failed the error in the log is still showing as 407.  Here is the latest log file:

[PDS.WITSMLstudio.Desktop.2.log.txt](https://github.com/pds-technology/witsml-studio/files/865285/PDS.WITSMLstudio.Desktop.2.log.txt)

**Comment by bmdiaz** [comment]
We've added an option on the Proxy tab to enable the use of your default credentials.  Please give that a try and let me know if that works.

![image](https://cloud.githubusercontent.com/assets/235309/24280917/98fe65b0-1022-11e7-8679-0f2881600b8d.png)

**Comment by StreckerCM** [comment]
That fix worked!  Thank you!
