### ISSUE TITLE
.NET Framework 4 does not support TLS 1.2 by default

### ISSUE THREAD

**Issue by nilsbenson** [pds-technology/witsml-studio#4]
We recently updated the SSL cert on our public sites to a brand new Comodo SSL wildcard. SSL3 has been slated for death/deprecation for several years, with a hard deadline for at least Firefox of June 2017. Moving forward the "good" method is to use TLS 1.2, which is not support by default as a protocol for any ServicePointManager-related network requests in v4 of the framework. Moving to 4.5 solves the issue, or manually allowing TLS 1.2 on the connections vis the ServicePointManager does as well. 

Our internal and public applications have no issues communicating with the servers and are on v4.5. Just updating the framework version appears to be enough.

**Comment by nilsbenson** [comment]
actually, looking in to this farther there is some other issue. By using the older Energistics Sample Browser App I am able to connect via SSL with the new cert, but not with PDS.Witsml. I guess I will clone the repo and see what I can determine.

**Comment by nilsbenson** [comment]
After testing the latest code in the repo, this bug is not reproducible. It happens consistently on the currently release ClickOnce build, but not from the current source.

**Comment by bmdiaz** [comment]
What version of the click-once installed client application are you running?  There was a breaking change in the installer back in March that required users to uninstall/reinstall in order to continue to receive the latest updates.  This is what the About dialog from the latest version should look like:

![image](https://cloud.githubusercontent.com/assets/235309/26162597/c2f4adee-3aec-11e7-8a6f-1d9fa7f16599.png)

Visit our [Downloads](https://witsml.pds.technology/docs/downloads/) page if you need to reinstall the latest version.

**Comment by nilsbenson** [comment]
Bobby,

That was the problem. I uninstalled the older build and installed the latest from the web site and it worked.

Thanks!

Nils
